# Generated by Django 3.0.9 on 2020-08-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Bill'},
        ),
        migrations.AlterModelOptions(
            name='billdetails',
            options={'verbose_name': 'Bill Detail'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='companyaccount',
            options={'verbose_name_plural': 'Company Account'},
        ),
        migrations.AlterModelOptions(
            name='companybank',
            options={'verbose_name_plural': 'Company Bank'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'verbose_name': 'Customer Request'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='employeebank',
            options={'verbose_name_plural': 'Employee Banks'},
        ),
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'verbose_name_plural': 'Employee Salary'},
        ),
        migrations.AlterModelOptions(
            name='medicaldetails',
            options={'verbose_name_plural': 'Medical Details'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicine'},
        ),
    ]
